version: "1"
services:
  - type: web
    name: Swagger Web
    runtime: python
    repo: https://github.com/WM-AI-TECH-IA/GD-A
    plan: starter
    region: virginia
    buildCommand: pip install fastapi uvicorn
    startCommand: python verifier.py
    rootDir: swagger_server/
