version: "1"
services:
  - type: web
    name: Swagger Web
    runtime: python
    repo: https://github.com/WM-AI-TECH-IA/GD-A
    plan: starter
    region: virginia
    buildCommand: echo "No build needed"
    startCommand: uvicorn gpt_memory_builder:app --host 0.0.0.0 --port 5000
    rootDir: swagger_ui/
