openapi: 3.0.0
info:
  title: GD-AURORA SHELL API
  version: 1.0.0
  description: >
    Swagger Shell API simulant léxécution de scripts terminaux GD-AURORAPERO
servers:
  - url: https://gda-aurora-shell.render.com
    description: Point d'entrée simulé Render / Termux / Git
paths:
  //exec/aurora:
    post:
      summary: GÀ Execution d'un ordre autonome par texte json
      operationId: auroraPost
      requestBody:
        required: [message]
        type: object
        properties:
          message:
            type: string
      responses:
        '200':
          description: Réponse genérée par terminal GD-AURSORA
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Bienvenu, membre est control si je suis nou."
