version: "1"
services:
  - type: web
    name: GD-A
    runtime: python
    repo: https://github.com/WM-AI-TECH-IA/GD-A
    plan: starter
    region: virginia
    buildCommand: pip install -r requirements.txt
    startCommand: python boot.py
    rootDir: gda_node_optima/