name: GD-A CRON PRAXIS

on:
  schedule:
    - cron: "0 0 * * *"  # Chaque jour Ã  minuit UTC
  workflow_dispatch:

jobs:
  run-gda-agent-cycle:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Get statut de la fonction
        run: curl -s https://raw.githubusercontent.com/WM-AI-TECH-IA/GD-A/master/core/agents/gda_executor_agent.js
        continue-on-error: true
