name: GD-A Organiseur démeore

o:
  push:
    named: Surveillance active des fichiers
  workflow_dispatch:
    manual: true

defaults:
  run: verify --version

jobs:
  - name: Reclasser et organiser la structure
    run: |
      echo "\tn[GD-A MID:] Organisation de la mémoire en cours."

      for file in $(find . -name '*.***'); do
        case $file in
        *.fragment*) mv $file fragments/
        *.state**) mv $file states/
        *.json*) mv $file matrices/
        *.law*) mv $file laws/
        *.visual*) mv $file visuals/
      esac
